-- Emotion labeling app - Supabase setup
--
-- Run this whole file in the Supabase SQL editor (Dashboard -> SQL Editor ->
-- New query -> paste -> Run). It is idempotent: it is safe to run on a project
-- where the tables and functions already exist.
--
-- Section 3 DROPS and recreates the three functions. On a project where they
-- already work you do not need this file at all - it is here to rebuild the
-- schema on a new project, or to re-assert the grants. Section 5 (the reporting
-- view) can be run on its own.
--
-- What it guarantees:
--   1. The four tables exist with the expected columns and keys.
--   2. Row Level Security is on, and anonymous visitors get NO direct table
--      access - they can only reach the database through the three RPCs below.
--   3. The three RPCs the app calls exist with exactly the signatures the app
--      sends, run as SECURITY DEFINER, and are executable with the anon key.
--      This is what makes the app work for outside participants.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- 1. Tables
-- ---------------------------------------------------------------------------

create table if not exists public.participants (
    participant_id uuid primary key default gen_random_uuid(),
    user_id text not null,
    created_at timestamptz not null default now()
);

-- ON CONFLICT (user_id) in start_labeling_submission needs this unique index.
-- The name matches the default Postgres name, so an existing UNIQUE constraint
-- on user_id makes this a no-op.
create unique index if not exists participants_user_id_key
    on public.participants (user_id);

create table if not exists public.questions (
    question_id bigint generated by default as identity primary key,
    question_text text not null,
    correct_emotion text,
    created_at timestamptz not null default now()
);

create table if not exists public.submissions (
    submission_id uuid primary key default gen_random_uuid(),
    participant_id uuid not null references public.participants (participant_id),
    started_at timestamptz not null default now(),
    submitted_at timestamptz,
    completed boolean not null default false
);

create table if not exists public.responses (
    response_id bigint generated by default as identity primary key,
    submission_id uuid not null references public.submissions (submission_id),
    question_id bigint not null references public.questions (question_id),
    selected_emotion text not null,
    created_at timestamptz not null default now()
);

create index if not exists submissions_participant_id_idx
    on public.submissions (participant_id);
create index if not exists responses_submission_id_idx
    on public.responses (submission_id);
create index if not exists responses_question_id_idx
    on public.responses (question_id);

-- ---------------------------------------------------------------------------
-- 2. Row Level Security
-- ---------------------------------------------------------------------------
-- RLS is enabled with no policies, so the anon and authenticated roles cannot
-- read or write these tables directly. All writes go through the SECURITY
-- DEFINER functions below, which is why the app uses RPCs instead of
-- .table(...).insert(...). service_role (and the SQL editor) still sees
-- everything.

alter table public.participants enable row level security;
alter table public.questions    enable row level security;
alter table public.submissions  enable row level security;
alter table public.responses    enable row level security;

revoke all on public.participants from anon;
revoke all on public.questions    from anon;
revoke all on public.submissions  from anon;
revoke all on public.responses    from anon;

-- ---------------------------------------------------------------------------
-- 3. RPC functions
-- ---------------------------------------------------------------------------
-- Drop every existing overload first, so PostgREST never has to choose between
-- two signatures with the same name.

do $drop_rpcs$
declare
    routine record;
begin
    for routine in
        select p.oid::regprocedure as signature
        from pg_proc p
        join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public'
          and p.proname in (
              'emotion_labeling_healthcheck',
              'start_labeling_submission',
              'complete_labeling_submission'
          )
    loop
        execute format('drop function if exists %s cascade', routine.signature);
    end loop;
end
$drop_rpcs$;

-- 3a. Health check - the app calls this before letting a participant start.

create function public.emotion_labeling_healthcheck()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $healthcheck$
    select to_regclass('public.participants') is not null
       and to_regclass('public.questions')    is not null
       and to_regclass('public.submissions')  is not null
       and to_regclass('public.responses')    is not null;
$healthcheck$;

-- 3b. Start a submission: upsert the anonymous participant, open a submission,
-- and register the five sampled messages. Returns the submission id plus the
-- question ids in the same order they were sent.

create function public.start_labeling_submission(
    p_user_id text,
    p_questions jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $start_submission$
declare
    v_user_id        text := btrim(coalesce(p_user_id, ''));
    v_participant_id uuid;
    v_submission_id  uuid;
    v_question       jsonb;
    v_text           text;
    v_emotion        text;
    v_question_id    bigint;
    v_questions      jsonb := '[]'::jsonb;
begin
    if length(v_user_id) < 8 or length(v_user_id) > 100 then
        raise exception 'A participant ID of 8 to 100 characters is required.';
    end if;

    if p_questions is null
       or jsonb_typeof(p_questions) <> 'array'
       or jsonb_array_length(p_questions) = 0
       or jsonb_array_length(p_questions) > 20 then
        raise exception 'Between 1 and 20 questions are required.';
    end if;

    insert into public.participants (user_id)
    values (v_user_id)
    on conflict (user_id) do update set user_id = excluded.user_id
    returning participant_id into v_participant_id;

    insert into public.submissions (participant_id)
    values (v_participant_id)
    returning submission_id into v_submission_id;

    for v_question in select value from jsonb_array_elements(p_questions)
    loop
        v_text := btrim(coalesce(v_question ->> 'question_text', ''));
        v_emotion := lower(btrim(coalesce(v_question ->> 'correct_emotion', '')));

        if length(v_text) = 0 or length(v_text) > 2000 then
            raise exception 'Each question needs question_text of up to 2000 characters.';
        end if;

        if v_emotion not in ('anger', 'fear', 'joy', 'love', 'sadness', 'surprise') then
            v_emotion := 'unknown';
        end if;

        select q.question_id
        into v_question_id
        from public.questions q
        where q.question_text = v_text
          and coalesce(q.correct_emotion, '') = v_emotion
        limit 1;

        if v_question_id is null then
            insert into public.questions (question_text, correct_emotion)
            values (v_text, v_emotion)
            returning question_id into v_question_id;
        end if;

        v_questions := v_questions || jsonb_build_object(
            'question_id', v_question_id,
            'question_text', v_text
        );
    end loop;

    return jsonb_build_object(
        'submission_id', v_submission_id,
        'questions', v_questions
    );
end
$start_submission$;

-- 3c. Complete a submission: store one label per question and mark the
-- submission finished. Re-running it for the same submission replaces that
-- submission's labels instead of duplicating them.

create function public.complete_labeling_submission(
    p_submission_id uuid,
    p_responses jsonb
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $complete_submission$
begin
    if p_submission_id is null
       or not exists (
           select 1
           from public.submissions s
           where s.submission_id = p_submission_id
       ) then
        raise exception 'Unknown submission.';
    end if;

    if p_responses is null
       or jsonb_typeof(p_responses) <> 'array'
       or jsonb_array_length(p_responses) = 0
       or jsonb_array_length(p_responses) > 20 then
        raise exception 'Between 1 and 20 responses are required.';
    end if;

    if exists (
        select 1
        from jsonb_array_elements(p_responses) as element
        where lower(btrim(coalesce(element.value ->> 'selected_emotion', '')))
              not in ('anger', 'fear', 'joy', 'love', 'sadness', 'surprise')
    ) then
        raise exception 'Each response needs one of the six supported emotions.';
    end if;

    if exists (
        select 1
        from jsonb_array_elements(p_responses) as element
        where not exists (
            select 1
            from public.questions q
            where q.question_id = (element.value ->> 'question_id')::bigint
        )
    ) then
        raise exception 'A response referenced an unknown question.';
    end if;

    delete from public.responses r
    where r.submission_id = p_submission_id;

    insert into public.responses (submission_id, question_id, selected_emotion)
    select
        p_submission_id,
        (element.value ->> 'question_id')::bigint,
        lower(btrim(element.value ->> 'selected_emotion'))
    from jsonb_array_elements(p_responses) as element;

    update public.submissions
    set completed = true,
        submitted_at = now()
    where submission_id = p_submission_id;

    return true;
end
$complete_submission$;

-- ---------------------------------------------------------------------------
-- 4. Function access for anonymous participants
-- ---------------------------------------------------------------------------

revoke execute on function public.emotion_labeling_healthcheck()            from public;
revoke execute on function public.start_labeling_submission(text, jsonb)    from public;
revoke execute on function public.complete_labeling_submission(uuid, jsonb) from public;

grant execute on function public.emotion_labeling_healthcheck()            to anon, authenticated;
grant execute on function public.start_labeling_submission(text, jsonb)    to anon, authenticated;
grant execute on function public.complete_labeling_submission(uuid, jsonb) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 5. Reporting view (owner only - not exposed to the anon key)
-- ---------------------------------------------------------------------------
-- Answers "which anonymous participant labeled which message with which label".

drop view if exists public.labeling_results;

create view public.labeling_results
with (security_invoker = true)
as
select
    p.user_id,
    s.submission_id,
    s.submitted_at,
    s.completed,
    q.question_id,
    q.question_text,
    q.correct_emotion,
    r.selected_emotion,
    (r.selected_emotion = q.correct_emotion) as matches_dataset_label
from public.responses r
join public.submissions s  on s.submission_id = r.submission_id
join public.participants p on p.participant_id = s.participant_id
join public.questions q    on q.question_id = r.question_id;

revoke all on public.labeling_results from anon;

-- ---------------------------------------------------------------------------
-- 6. Smoke test (optional - run these after the script)
-- ---------------------------------------------------------------------------
-- select public.emotion_labeling_healthcheck();            -- expect: true
-- select count(*) from public.labeling_results;
-- select * from public.labeling_results order by submitted_at desc limit 20;
